Поменял функцию
NorthGateVologda/NorthGateDBScripts pull request #5
Opened 2023-08-05 18:01 UTC by sshiae

Поменял функцию

2023-08-05 20:32 UTC, olgapshen requested changes
Тём, перепиши пожалуйста на пробелы...

2023-08-05 20:32 UTC, olgapshen commented on northgate/FUNCTIONS/FNC_GET_RECOMMENDATION_PLACEMENT_PARKS_JSON.sql
> +										   FLOOR(p.population) AS population,
Тём, можешь пожалуйста использовать пробелы заместо табов?

2023-08-05 20:33 UTC, olgapshen commented
И снова лейбочки и проект забыли проставить :(

2023-08-05 22:21 UTC, sshiae commented on northgate/FUNCTIONS/FNC_GET_RECOMMENDATION_PLACEMENT_PARKS_JSON.sql
> +										   FLOOR(p.population) AS population,
Хорошо

2023-08-05 23:27 UTC, lvapl approved these changes, later dismissed

2023-08-06 00:00 UTC, sshiae commented on northgate/FUNCTIONS/FNC_GET_RECOMMENDATION_PLACEMENT_PARKS_JSON.sql
> +										   FLOOR(p.population) AS population,
Исправил

2023-08-06 17:56 UTC, olgapshen approved these changes
Просто супер!!!

2023-08-06 17:57 UTC, olgapshen commented on northgate/FUNCTIONS/FNC_GET_RECOMMENDATION_PLACEMENT_PARKS_JSON.sql
> +										   FLOOR(p.population) AS population,
Супер!!!

2023-08-06 17:57 UTC, merged